Repository DynamoDS/Dynamo, pull requests merged in 2018-12, with the labels that each got.

#9290 Add ParseJSON and StringifyJSON to core library
  src/Libraries/CoreNodes/CoreNodes.csproj
  src/Libraries/CoreNodes/Data.cs
  src/LibraryViewExtension/web/library/layoutSpecs.json
  test/DynamoCoreTests/DSCoreDataTests.cs
  test/DynamoCoreTests/DynamoCoreTests.csproj
  test/core/json/JSONFile.json
  test/core/json/JSON_Nodes_DesignScript.dyn
  test/core/json/JSON_Nodes_PythonJSONParsing.dyn
  test/core/json/JSON_Nodes_Replication.dyn
  test/core/json/JSON_Nodes_Test.dyn
Labels: LGTM

#9294 Remove Show/Hide geometry preview upstream
  src/DynamoCoreWpf/Commands/WorkspaceCommands.cs
  src/DynamoCoreWpf/Properties/Resources.Designer.cs
  src/DynamoCoreWpf/Properties/Resources.en-US.resx
  src/DynamoCoreWpf/Properties/Resources.resx
  src/DynamoCoreWpf/ViewModels/Core/WorkspaceViewModel.cs
  src/DynamoCoreWpf/Views/Core/WorkspaceView.xaml
  src/VisualizationTests/HelixWatch3DViewModelTests.cs
Labels: LGTM

#9292 update to new greg dll
  src/DynamoCore/DynamoCore.csproj
  src/DynamoCore/packages.config
  src/DynamoCoreWpf/DynamoCoreWpf.csproj
  src/DynamoCoreWpf/packages.config
  src/DynamoPackages/DynamoPackages.csproj
  src/DynamoPackages/packages.config
  src/LibraryViewExtension/LibraryViewExtension.csproj
  src/LibraryViewExtension/packages.config
  test/DynamoCoreTests/DynamoCoreTests.csproj
  test/DynamoCoreTests/packages.config
  test/DynamoCoreWpfTests/DynamoCoreWpfTests.csproj
  test/DynamoCoreWpfTests/packages.config
  test/Libraries/PackageManagerTests/PackageManagerTests.csproj
  test/Libraries/PackageManagerTests/packages.config
Labels: PTAL

#9296 Add marshaling between Dynamo and Python dictionaries
  src/DynamoUtilities/DataMarshaler.cs
  src/Libraries/DSIronPython/DSIronPython.csproj
  src/Libraries/DSIronPython/IronPythonEvaluator.cs
  test/DynamoCoreTests/DSEvaluationUnitTestBase.cs
  test/Libraries/DynamoPythonTests/PythonEditTests.cs
  test/core/json/JSON_Nodes_PythonJSONParsing.dyn
  test/core/python/netDict_from_python.dyn
  test/core/python/python_dict.dyn
  test/core/python/python_dict2.dyn
Labels: LGTM

#9312 QNTM-5870: When searching weights should be taken into account before string matching
  src/DynamoCore/Models/DynamoModel.cs
  src/DynamoCore/Search/NodeSearchModel.cs
  src/DynamoCore/Search/SearchDictionary.cs
  src/DynamoCore/Search/SearchLibrary.cs
  src/DynamoCoreWpf/Properties/Resources.Designer.cs
  src/DynamoCoreWpf/Properties/Resources.en-US.resx
  src/DynamoCoreWpf/Properties/Resources.resx
  src/DynamoCoreWpf/ViewModels/Core/DynamoViewModel.cs
  src/DynamoCoreWpf/Views/Core/DynamoView.xaml
Labels: LGTM

#9287 Crash creating automatic backup of Custom Node with special Characters
  src/DynamoCoreWpf/Properties/Resources.Designer.cs
  src/DynamoCoreWpf/Properties/Resources.en-US.resx
  src/DynamoCoreWpf/Properties/Resources.resx
  src/DynamoCoreWpf/UI/Prompts/FunctionNamePrompt.xaml.cs
  src/DynamoUtilities/PathHelper.cs
  test/DynamoCoreTests/UtilityTests.cs
Labels: 2.x, LGTM, bug

#9315 DYN-1440: Remove unneeded debug logging information
  src/LibraryViewExtension/Handlers/ResourceHandlerFactory.cs
Labels: LGTM

#9306 Enable package node migration for Dynamo Core 2.0+ graphs
  src/DynamoCore/Graph/Workspaces/SerializationConverters.cs
  src/DynamoCore/Graph/Workspaces/WorkspaceModel.cs
  test/DynamoCoreTests/DynamoCoreTests.csproj
  test/DynamoCoreTests/NodeMigrationTests.cs
  test/pkgs/Dynamo Samples/bin/SampleLibraryUI.dll
  test/pkgs/Dynamo Samples/bin/SampleLibraryZeroTouch.Migrations.xml
  test/pkgs/Dynamo Samples/bin/SampleLibraryZeroTouch.dll
  test/pkgs/Dynamo Samples/extra/LegacyPackageSampleGraph.dyn
  test/pkgs/Dynamo Samples/pkg.json
Labels: LGTM

#9023 Fix unmarshaling of nested DS Dictionary
  src/Engine/ProtoCore/FFI/CLRObjectMarshaler.cs
  test/DynamoCoreTests/CodeBlockNodeTests.cs
  test/DynamoCoreTests/DynamoCoreTests.csproj
  test/DynamoCoreTests/Nodes/DictionaryTests.cs
  test/DynamoCoreWpfTests/WatchNodeTests.cs
  test/Engine/FFITarget/DummyCollection.cs
  test/core/dictionary/AcceptArbitraryDict.dyn
  test/core/dictionary/AcceptDictWithType.dyn
  test/core/dictionary/AcceptNestedDictionary.dyn
Labels: PTAL, WIP

#9320 Update preview for multi-output node when disconnecting it
  src/DynamoCore/Graph/Nodes/FunctionCallNodeController.cs
  test/DynamoCoreWpfTests/DynamoCoreWpfTests.csproj
  test/DynamoCoreWpfTests/RecordedTests.cs
  test/core/recorded/multioutput_node_preview.xml
Labels: LGTM

#9326 Fix Typos
  doc/distrib/Samples/en-US/Basics/Basics_Basic01.dyn
  src/Libraries/CoreNodes/String.cs
Labels: LGTM

#9334 Heterogeneous list update gives infinite loop
  src/Engine/ProtoCore/Lang/Replication/Replicator.cs
  test/DynamoCoreTests/DSEvaluationModelTest.cs
  test/core/dsevaluation/test_hetereogenous_list.dyn
Labels: LGTM
