Repository DynamoDS/Dynamo, pull requests merged in 2018-11, with the labels that each got.

#9230 DYN-942: Actions, Query, Create icons fail to load every time a search is executed
  src/LibraryViewExtension/web/library/librarie.min.js
Labels: LGTM

#9233 [Cherry-pick] Include several 2.1 (master) fixes & changes in 2.02
  src/DynamoCore/Graph/Nodes/CustomNodes/CustomNodeController.cs
  src/DynamoCoreWpf/ViewModels/RenderPackageFactoryViewModel.cs
  src/DynamoCoreWpf/Views/Core/DynamoView.xaml
  src/DynamoCoreWpf/Views/Preview/PreviewControl.xaml.cs
  src/Libraries/CoreNodes/List.cs
  src/LibraryViewExtension/web/library/librarie.min.js
  src/LibraryViewExtension/web/library/library.html
  src/NodeServices/Analytics.cs
  test/DynamoCoreTests/AnalyticsTests.cs
  test/DynamoCoreTests/CustomNodes.cs
  test/DynamoCoreTests/Nodes/ListTests.cs
  test/core/list/ListMaximumItem.dyn
  test/core/multiout/partial-multiout-customnode.dyf
  test/core/multiout/partial-multiout-customnode.dyn
Labels: LGTM

#9240 Address race condition where library resources attempt to load before the Browser completes loading
  src/LibraryViewExtension/Handlers/ResourceHandlerFactory.cs
  src/LibraryViewExtension/LibraryViewController.cs
  src/LibraryViewExtension/web/library/library.html
Labels: LGTM

#9241 Port model API change
  src/DynamoCore/Graph/Nodes/PortModel.cs
Labels: LGTM

#9242 Fix broken behavior of IsVisibleInDynamoLibrary attribute with interfaces and Enums
  src/Engine/ProtoCore/FFI/CLRDLLModule.cs
  src/Libraries/CoreNodes/DateTime.cs
  test/DynamoCoreWpfTests/LibraryTests.cs
  test/Engine/FFITarget/CodeCompletionClass.cs
Labels: LGTM

#9251 Additional cleanup to the LibraryViewController
  src/LibraryViewExtension/LibraryViewController.cs
Labels: LGTM

#9182 KeepListStructure list@level functionality should work.
  src/DynamoCore/Graph/Nodes/NodeModel.cs
  test/DynamoCoreWpfTests/ListAtLevelTest.cs
  test/UI/keepListStructure.dyn
Labels: 2.x, PTAL, bug

#9257 Ensure changes to IsInput & IsOutput mark the node/graph as modified
  src/DynamoCore/Graph/Nodes/NodeModel.cs
  src/DynamoCoreWpf/Views/Core/NodeView.xaml.cs
  test/DynamoCoreWpfTests/NodeViewTests.cs
Labels: LGTM

#9269 QNTM-5426: Adding null checks to harden return from CreateNodeFromShortName
  src/DynamoCore/Engine/NodeToCode/NodeToCode.cs
  src/DynamoCore/Graph/Nodes/CodeBlockNode.cs
  src/Engine/ProtoCore/MigrationRewriter.cs
  src/Engine/ProtoCore/Namespace/ElementRewriter.cs
  src/Engine/ProtoCore/SyntaxAnalysis/AssociativeAstVisitor.cs
  src/Engine/ProtoCore/SyntaxAnalysis/AstVisitor.cs
  src/Engine/ProtoCore/Utils/CompilerUtils.cs
  src/Engine/ProtoCore/Utils/CoreUtils.cs
Labels: LGTM

#9250 Update Nuspecs Net folder version
  tools/NuGet/template-artifactory/DynamoVisualProgramming.DynamoCoreRuntime.nuspec
  tools/NuGet/template-artifactory/DynamoVisualProgramming.SignDynamo.nuspec
  tools/NuGet/template-nuget/DynamoVisualProgramming.Core.nuspec
  tools/NuGet/template-nuget/DynamoVisualProgramming.DynamoCoreNodes.nuspec
  tools/NuGet/template-nuget/DynamoVisualProgramming.DynamoServices.nuspec
  tools/NuGet/template-nuget/DynamoVisualProgramming.Tests.nuspec
  tools/NuGet/template-nuget/DynamoVisualProgramming.WpfUILibrary.nuspec
  tools/NuGet/template-nuget/DynamoVisualProgramming.ZeroTouchLibrary.nuspec
Labels: LGTM

#9274 Add Zip/UnZip Tests
  doc/distrib/License.rtf
  src/DynamoCore/DynamoCore.csproj
  src/DynamoCore/Ionic.Zip.xml
  src/DynamoCore/packages.config
  src/DynamoCoreWpf/DynamoCoreWpf.csproj
  src/DynamoCoreWpf/Ionic.Zip.xml
  src/DynamoCoreWpf/packages.config
  src/DynamoPackages/DynamoPackages.csproj
  src/DynamoPackages/Ionic.Zip.xml
  src/DynamoPackages/packages.config
  src/LibraryViewExtension/LibraryViewExtension.csproj
  src/LibraryViewExtension/packages.config
  test/DynamoCoreTests/DynamoCoreTests.csproj
  test/DynamoCoreTests/packages.config
  test/DynamoCoreWpfTests/DynamoCoreWpfTests.csproj
  test/DynamoCoreWpfTests/Ionic.Zip.xml
  test/DynamoCoreWpfTests/packages.config
  test/Libraries/PackageManagerTests/PackageManagerTests.csproj
  test/Libraries/PackageManagerTests/PackageUploadBuilderTests.cs
  test/Libraries/PackageManagerTests/packages.config
  test/ViewExtensionLibraryTests/packages.config
  test/pkgs/the-Saurus/bin/Accord.MachineLearning.dll
  test/pkgs/the-Saurus/bin/Accord.Math.Core.dll
  test/pkgs/the-Saurus/bin/Accord.Math.dll
  test/pkgs/the-Saurus/bin/Accord.Statistics.dll
  test/pkgs/the-Saurus/bin/Accord.dll
  test/pkgs/the-Saurus/bin/GalaSoft.MvvmLight.Extras.dll
  test/pkgs/the-Saurus/bin/GalaSoft.MvvmLight.Platform.dll
  test/pkgs/the-Saurus/bin/GalaSoft.MvvmLight.dll
  test/pkgs/the-Saurus/pkg.json
Labels: PTAL
