Repository DynamoDS/Dynamo, pull requests merged in 2018-03, with the labels that each got.

#8605 fix CBN in error state undo/redo crash.
  src/DynamoCore/Graph/Nodes/CodeBlockNode.cs
  test/DynamoCoreTests/CodeBlockNodeTests.cs
Labels: LGTM

#8611 update ironPython dlls to 2.7.3 versions
  extern/IronPython/IronPython.Modules.dll
  extern/IronPython/IronPython.dll
  extern/IronPython/Microsoft.Dynamic.dll
  extern/IronPython/Microsoft.Scripting.Metadata.dll
  extern/IronPython/Microsoft.Scripting.dll
  src/Libraries/DSIronPython/DSIronPython.csproj
  src/Libraries/PythonNodeModels/PythonNodeModels.csproj
  src/Libraries/PythonNodeModelsWpf/PythonNodeModelsWpf.csproj
  test/Libraries/DynamoPythonTests/IronPythonTests.csproj
Labels: LGTM

#8615 Deprecate GetKeys, GetValues, ContainsKey, RemoveKey nodes
  src/DynamoCore/BuiltInAndOperators/BuiltIn.Migrations.xml
  src/DynamoCore/BuiltInAndOperators/BuiltIn.xml
  src/DynamoCore/BuiltInAndOperators/BuiltInImages.resx
  src/DynamoCore/Library/LibraryServices.cs
  src/Engine/ProtoCore/ExtendedLibraries/BuiltIn.ds
  src/Engine/ProtoCore/Lang/BuiltInFunctionEndPoint.cs
  src/Engine/ProtoCore/Lang/BuiltInMethods.cs
  src/Engine/ProtoCore/Properties/Resources.Designer.cs
  src/Engine/ProtoCore/Properties/Resources.en-US.resx
  src/Engine/ProtoCore/Properties/Resources.resx
  src/Libraries/CoreNodes/DSCoreNodesImages.resx
  src/LibraryViewExtension/web/library/layoutSpecs.json
  test/DynamoCoreTests/CodeBlockNodeTests.cs
  test/Engine/ProtoTest/TD/MultiLangTests/Builtin_Functions.cs
  test/ViewExtensionLibraryTests/resources/libraryItems.json
Labels: PTAL

#8616 QNTM-3393: Performance issue in this VW graph
  src/Engine/ProtoCore/RuntimeData.cs
Labels: PTAL

#8623 Do not update FileName on save for backups or customNodes
  src/DynamoCore/Graph/Workspaces/WorkspaceModel.cs
  src/DynamoCoreWpf/ViewModels/Core/DynamoViewModel.cs
  src/DynamoCoreWpf/ViewModels/Core/WorkspaceViewModel.cs
  test/DynamoCoreWpfTests/WorkspaceSaving.cs
Labels: 2.0 Release

#8631 Dynamo migration change
  src/DynamoCore/Core/DynamoMigrator.cs
  test/DynamoCoreTests/UserDataMigrationTests.cs
Labels: PTAL

#8626 Polymorphic dispatch for static function groups
  src/Engine/ProtoAssociative/CodeGen.cs
  src/Engine/ProtoCore/ClassTable.cs
  src/Engine/ProtoCore/FFI/CLRDLLModule.cs
  src/Engine/ProtoCore/Lang/CallSite.cs
  src/Engine/ProtoCore/Parser/AssociativeAST.cs
  test/DynamoCoreTests/DynamoCoreTests.csproj
  test/DynamoCoreTests/InheritanceTests.cs
  test/Engine/FFITarget/InheritenceTests.cs
  test/core/inheritance/inheritanceA.dyn
  test/core/inheritance/inheritanceB.dyn
  test/core/inheritance/inheritanceC.dyn
  test/core/inheritance/inheritanceD.dyn
  test/core/inheritance/inheritanceE.dyn
Labels: LGTM

#8618 QNTM-3261: Prevent variable redefinition in function definitions and associative blocks
  src/Engine/ProtoCore/Utils/CompilerUtils.cs
  test/DynamoCoreTests/CodeBlockNodeTests.cs
  test/core/dsevaluation/TestVarRecursiveDepInAssocBlock.dyn
  test/core/dsevaluation/TestVarRecursiveDepInFunctionDef.dyn
  test/core/dsevaluation/TestVarRedefinitionInAssocBlock.dyn
  test/core/dsevaluation/TestVarRedefinitionInFunctionDef.dyn
Labels: 2.0 Release

#8642 fix localization error
  src/DynamoCore/Graph/Workspaces/WorkspaceInfo.cs
Labels: PTAL

#8649 Fix static property compilation and crash
  src/DynamoCore/Graph/Nodes/ZeroTouch/DSFunctionBase.cs
  src/Engine/ProtoAssociative/CodeGen.cs
  src/Engine/ProtoCore/FFI/CLRObjectMarshaler.cs
  test/DynamoCoreTests/NodeToCodeTest.cs
  test/Engine/ProtoTest/Associative/MethodsFocusTeam.cs
  test/core/node2code/tostaticproperty.dyn
Labels: 2.0 Release

#8648 QNTM-3646: Fix creation of unwanted input port for list index-assignment
  src/DynamoCore/Graph/Nodes/CodeBlockNode.cs
  src/DynamoCore/Graph/Nodes/CodeBlockUtils.cs
  src/DynamoCoreWpf/Properties/Resources.Designer.cs
  src/DynamoCoreWpf/Properties/Resources.en-US.resx
  src/DynamoCoreWpf/Properties/Resources.resx
  src/Engine/ProtoAssociative/CodeGen.cs
  src/Libraries/CoreNodes/DSCoreNodesImages.resx
  src/LibraryViewExtension/web/library/layoutSpecs.json
  test/DynamoCoreTests/CodeBlockNodeTests.cs
  test/DynamoCoreTests/NodeToCodeTest.cs
  test/DynamoCoreWpfTests/RecordedTests.cs
Labels: 2.0 Release, PTAL

#8660 Cherry-pick #8649 and #8648
  src/DynamoCore/Graph/Nodes/CodeBlockNode.cs
  src/DynamoCore/Graph/Nodes/CodeBlockUtils.cs
  src/DynamoCore/Graph/Nodes/ZeroTouch/DSFunctionBase.cs
  src/DynamoCoreWpf/Properties/Resources.Designer.cs
  src/DynamoCoreWpf/Properties/Resources.en-US.resx
  src/DynamoCoreWpf/Properties/Resources.resx
  src/Engine/ProtoAssociative/CodeGen.cs
  src/Engine/ProtoCore/FFI/CLRObjectMarshaler.cs
  src/Libraries/CoreNodes/DSCoreNodesImages.resx
  src/LibraryViewExtension/web/library/layoutSpecs.json
  test/DynamoCoreTests/CodeBlockNodeTests.cs
  test/DynamoCoreTests/NodeToCodeTest.cs
  test/DynamoCoreWpfTests/RecordedTests.cs
  test/Engine/ProtoTest/Associative/MethodsFocusTeam.cs
  test/core/node2code/tostaticproperty.dyn
Labels: LGTM

#8661 QNTM-3279: Fix for crash when trying to directly call properties on class name
  src/AssemblySharedInfoGenerator/AssemblySharedInfo.cs
  src/Engine/ProtoAssociative/CodeGen.cs
  src/Engine/ProtoCore/FFI/CLRObjectMarshaler.cs
  src/Engine/ProtoCore/Utils/CoreUtils.cs
  test/Engine/FFITarget/ClassFunctionality.cs
  test/Engine/ProtoTest/Associative/MethodsFocusTeam.cs
Labels: 2.0 Release

#8657 [PTAL] Update Dynamo samples from xml to json
  doc/distrib/Samples/en-US/Basics/Basics_Basic01.dyn
  doc/distrib/Samples/en-US/Basics/Basics_Basic02.dyn
  doc/distrib/Samples/en-US/Basics/Basics_Basic03.dyn
  doc/distrib/Samples/en-US/Core/Core_AttractorPoint.dyn
  doc/distrib/Samples/en-US/Core/Core_CodeBlocks.dyn
  doc/distrib/Samples/en-US/Core/Core_ListAtLevel.dyn
  doc/distrib/Samples/en-US/Core/Core_ListLacing.dyn
  doc/distrib/Samples/en-US/Core/Core_Math.dyn
  doc/distrib/Samples/en-US/Core/Core_PassingFunctions.dyn
  doc/distrib/Samples/en-US/Core/Core_Python.dyn
  doc/distrib/Samples/en-US/Core/Core_RangeSyntax.dyn
  doc/distrib/Samples/en-US/Core/Core_Strings.dyn
  doc/distrib/Samples/en-US/Geometry/Geometry_Curves.dyn
  doc/distrib/Samples/en-US/Geometry/Geometry_Points.dyn
  doc/distrib/Samples/en-US/Geometry/Geometry_Solids.dyn
  doc/distrib/Samples/en-US/Geometry/Geometry_Surfaces.dyn
  doc/distrib/Samples/en-US/ImportExport/ImportExport_CSV to Stuff.dyn
  doc/distrib/Samples/en-US/ImportExport/ImportExport_Data To Excel.dyn
  doc/distrib/Samples/en-US/ImportExport/ImportExport_Excel to Dynamo.dyn
  doc/distrib/Samples/en-US/Revit/Revit_Adaptive Component Placement.dyn
  doc/distrib/Samples/en-US/Revit/Revit_Color.dyn
  doc/distrib/Samples/en-US/Revit/Revit_Floors and Framing.dyn
  doc/distrib/Samples/en-US/Revit/Revit_ImportSolid.dyn
  doc/distrib/Samples/en-US/Revit/Revit_PlaceFamiliesByLevel_Set Parameters.dyn
  doc/distrib/Samples/en-US/Revit/Revit_StructuralFraming.dyn
  test/DynamoCoreWpfTests/WorkspaceOpeningTests.cs
  test/Libraries/WorkflowTests/DynamoSamples.cs
Labels: LGTM

#8670 QNTM-3641: Prevent ColorRange node from crashing with old style List syntax
  src/Libraries/CoreNodeModelsWpf/NodeViewCustomizations/ColorRange.cs
  test/DynamoCoreTests/CodeBlockNodeTests.cs
  test/core/dsevaluation/colorRangeBad.dyn
Labels: LGTM

#8673 scroll bar fix in incanvas search
  src/DynamoCoreWpf/Views/Core/DynamoView.xaml.cs
Labels: LGTM

#8678 [WIP] QNTM-3710: Update changes from librarie.js to fix QNTM-3710
  src/LibraryViewExtension/web/library/librarie.min.js
Labels: LGTM

#8595 Add RegisterForTrace attribute as alternate trigger in Json serialization
  src/DynamoCore/Graph/Workspaces/SerializationConverters.cs
Labels: PTAL

#8686 DynamoPlayer FileOpenCommand Update
  src/DynamoCoreWpf/ViewModels/Core/DynamoViewModel.cs
Labels: LGTM

#8697 Updating Getting Started for Dynamo 2.0
  extern/gallery/Data/04-Place-L.png
  extern/gallery/Data/07-Packages.png
  extern/gallery/en-US/GalleryContents.xml
Labels: LGTM

#8698 Updating Getting Started for Dynamo 2.0 (#8697)
  extern/gallery/Data/04-Place-L.png
  extern/gallery/Data/07-Packages.png
  extern/gallery/en-US/GalleryContents.xml
Labels: LGTM

#8696 Addons section closes each time user creates an instance of any custom node
  src/DynamoCore/Core/CustomNodeManager.cs
  src/DynamoCore/Models/DynamoModel.cs
  src/DynamoCore/Search/SearchLibrary.cs
  src/DynamoCoreWpf/Properties/AssemblyInfo.cs
  src/DynamoCoreWpf/ViewModels/Search/SearchViewModel.cs
  src/LibraryViewExtension/LibraryViewController.cs
  test/DynamoCoreWpfTests/Utility/DispatcherUtil.cs
  test/ViewExtensionLibraryTests/LibraryViewControllerTests.cs
  test/ViewExtensionLibraryTests/ViewExtensionLibraryTests.csproj
Labels: PTAL

#8703 fix name property for NodeModels that are inputs
  src/DynamoCore/Graph/Workspaces/SerializationConverters.cs
Labels: LGTM
