Repository DynamoDS/Dynamo, pull requests merged in 2018-05, with the labels that each got.

#8816 Bump Hotfix branch to 2.0.1
  src/AssemblySharedInfoGenerator/AssemblySharedInfo.tt
Labels: LGTM

#8817 Bump Master to 2.1
  src/AssemblySharedInfoGenerator/AssemblySharedInfo.tt
Labels: LGTM

#8812 Save View info during Custom Node Info edition
  src/DynamoCoreWpf/NodeViewCustomization/NodeViewCustomizations/FunctionNodeViewCustomization.cs
  src/DynamoCoreWpf/ViewModels/Core/WorkspaceViewModel.cs
  test/DynamoCoreWpfTests/NodeViewCustomizationTests.cs
  test/DynamoCoreWpfTests/WorkspaceSaving.cs
Labels: 2.0.1 Release, Waiting for feedback

#8831 Update the Build number in the .cs file
  src/AssemblySharedInfoGenerator/AssemblySharedInfo.cs
Labels: LGTM

#8839 Update Build number
  src/AssemblySharedInfoGenerator/AssemblySharedInfo.tt
Labels: LGTM

#8840 Update build number
  src/AssemblySharedInfoGenerator/AssemblySharedInfo.cs
Labels: 2.0.1 Release, LGTM

#8825 comments are not serialized with custom node input nodes
  src/DynamoCore/Graph/Nodes/CustomNodes/Function.cs
  src/DynamoCore/Graph/Workspaces/SerializationConverters.cs
  src/DynamoCore/Graph/Workspaces/WorkspaceModel.cs
  src/DynamoCore/Library/TypedParameter.cs
  src/DynamoCoreWpf/ViewModels/Core/Converters/SerializationConverters.cs
  src/DynamoCoreWpf/ViewModels/Core/SerializationExtensions.cs
  test/DynamoCoreTests/CustomNodes.cs
  test/core/CustomNodes/inputNodesWithComments.dyf
Labels: 2.0.1 Release, LGTM

#8841 Save View info during Custom Node Info edition
  src/DynamoCoreWpf/NodeViewCustomization/NodeViewCustomizations/FunctionNodeViewCustomization.cs
  src/DynamoCoreWpf/ViewModels/Core/WorkspaceViewModel.cs
  test/DynamoCoreWpfTests/NodeViewCustomizationTests.cs
  test/DynamoCoreWpfTests/WorkspaceSaving.cs
Labels: 2.0.1 Release

#8843 Cherry picks
  src/DynamoCore/Graph/Nodes/CustomNodes/Function.cs
  src/DynamoCore/Graph/Workspaces/SerializationConverters.cs
  src/DynamoCore/Graph/Workspaces/WorkspaceModel.cs
  src/DynamoCore/Library/TypedParameter.cs
  src/DynamoCoreWpf/ViewModels/Core/Converters/SerializationConverters.cs
  src/DynamoCoreWpf/ViewModels/Core/SerializationExtensions.cs
  src/LibraryViewExtension/LibraryViewController.cs
  src/LibraryViewExtension/web/library/library.html
  test/DynamoCoreTests/CustomNodes.cs
  test/core/CustomNodes/inputNodesWithComments.dyf
Labels: 2.0.1 Release

#8824 QNTM 4211 - File Path node is missing in Player
  src/Libraries/CoreNodeModels/Input/FileSystem.cs
  test/core/isInput_isOutput/FilePath_DirectoryPath.dyn
Labels: 2.0.1 Release, LGTM

#8860 Update nuspec to include Newtonsoft.Json
  tools/NuGet/template-nuget/DynamoVisualProgramming.Core.nuspec
Labels: 2.0.1 Release

#8867 Signature change load failure
  src/DynamoCore/Graph/Workspaces/SerializationConverters.cs
  test/DynamoCoreTests/SerializationTests.cs
  test/core/serialization/functionSignatureDifferentNumParamsThanGraph.dyn
Labels: 2.0.1 Release, LGTM

#8868 2.0.1sigload
  src/DynamoCore/Graph/Workspaces/SerializationConverters.cs
  test/DynamoCoreTests/SerializationTests.cs
  test/core/serialization/functionSignatureDifferentNumParamsThanGraph.dyn
Labels: 2.0.1 Release

#8810 Fix type checking for integers on IsOutput serialization
  src/DynamoCore/Graph/Nodes/NodeInputData.cs
  src/DynamoCore/Graph/Nodes/NodeOutputData.cs
  test/core/isInput_isOutput/IsInput.dyn
  test/core/isInput_isOutput/IsOutput.dyn
Labels: 2.1 Release, LGTM

#8876 IsVisibleInDynamoLibrary Deserialization
  src/DynamoCore/Graph/Workspaces/SerializationConverters.cs
  test/DynamoCoreWpfTests/WorkspaceSaving.cs
Labels: 2.0.1 Release

#8900 AVP NumberInputNode deserialization
  src/Libraries/CoreNodeModels/Input/BaseTypes.cs
  test/DynamoCoreTests/CoreTests.cs
  test/core/number/TestNumberDeserialization.dyn
Labels: LGTM
