Repository DynamoDS/Dynamo, pull requests merged in 2019-03, with the labels that each got.

#9540 SelectInRegionCommand Removal in One test
  test/DynamoCoreWpfTests/RecordedTests.cs
  test/core/recorded/Defect_MAGN_520_DS.xml
Labels: LGTM

#9542 DYN-1476: AllowRankReductionAttribute on Zero Touch seems to be broken
  src/Engine/ProtoCore/FFI/CLRDLLModule.cs
  src/Engine/ProtoCore/FFI/CLRFFIFunctionPointer.cs
  test/Engine/FFITarget/TestObjects.cs
  test/Engine/ProtoTest/FFITests/CSFFITest.cs
Labels: LGTM

#9533 Provide a strategy for host integrator's to set the python template at startup
  src/DynamoCore/Models/DynamoModel.cs
  src/DynamoCore/Properties/Resources.Designer.cs
  src/DynamoCore/Properties/Resources.en-US.resx
  src/DynamoCore/Properties/Resources.resx
  test/DynamoCoreTests/Settings.cs
Labels: LGTM

#9550 DYN-1476 Follow Up: Remove Rank Reduction from Dictionary.Values
  src/Libraries/DesignScriptBuiltin/Dictionary.cs
Labels: LGTM

#9546 DYN-1175: Captured image name default to "graph name+timestamp".
  src/DynamoCoreWpf/ViewModels/Core/DynamoViewModel.cs
  src/DynamoUtilities/PathHelper.cs
  test/DynamoCoreTests/UtilityTests.cs
Labels: LGTM

#9549 Cherry Pick DYN-1476: AllowRankReductionAttribute on Zero Touch Properties (#9542)
  src/Engine/ProtoCore/FFI/CLRDLLModule.cs
  src/Engine/ProtoCore/FFI/CLRFFIFunctionPointer.cs
  src/Libraries/DesignScriptBuiltin/Dictionary.cs
  test/Engine/FFITarget/TestObjects.cs
  test/Engine/ProtoTest/FFITests/CSFFITest.cs
Labels: DNM

#9539 DYN-1639: Add performance test framework
  src/Dynamo.All.sln
  test/Performance/DynamoPerformanceTests/DynamoPerformanceTests.csproj
  test/Performance/DynamoPerformanceTests/PerformanceTestFramework.cs
  test/Performance/DynamoPerformanceTests/Properties/AssemblyInfo.cs
  test/Performance/DynamoPerformanceTests/app.config
  test/Performance/DynamoPerformanceTests/packages.config
Labels: LGTM

#9562 Cherry Pick: Render precision save (#9108)
  src/DynamoCore/Configuration/IPreferences.cs
  src/DynamoCore/Configuration/PreferenceSettings.cs
  src/DynamoCoreWpf/DynamoCoreWpf.csproj
  src/DynamoCoreWpf/ViewModels/Core/DynamoViewModel.cs
  src/DynamoCoreWpf/ViewModels/RenderPackageFactoryViewModel.cs
  test/DynamoCoreWpfTests/CoreUITests.cs
  test/settings/DynamoSettings-WithoutRenderPrecision.xml
Labels: LGTM

#9563 Upload daily Zip Build
  tools/autobuild/dynamo_s3.py
  tools/autobuild/installers_to_s3.py
Labels: LGTM

#9567 Duplicate connectors using `ctrl + left click` on input ports with testing
  src/DynamoCore/Models/DynamoModelCommands.cs
  src/DynamoCore/Models/RecordableCommands.cs
  src/DynamoCoreWpf/Commands/DynamoCommands.cs
  src/DynamoCoreWpf/ViewModels/Core/StateMachine.cs
  test/DynamoCoreWpfTests/RecordedTests.cs
  test/core/recorded/CtrlClickRecordedTestUndoRedo_Recording.xml
  test/core/recorded/CtrlClickRecordedTestUndo_Recording.xml
  test/core/recorded/CtrlClickRecordedTest_Recording.xml
Labels: LGTM

#9580 Address refactor bug introduced in #9567
  src/DynamoCore/Models/DynamoModelCommands.cs
  src/DynamoCoreWpf/Commands/DynamoCommands.cs
Labels: LGTM

#9585 Selective shift + click output connections grabs connectors for selected nodes only
  src/DynamoCore/Models/DynamoModelCommands.cs
  src/DynamoCoreWpf/ViewModels/Core/StateMachine.cs
  test/DynamoCoreWpfTests/RecordedTests.cs
  test/core/recorded/CombinationOfConnectorHotKeys_Recording.xml
  test/core/recorded/SelectiveShiftClickTestUndoRedo_Recording.xml
  test/core/recorded/SelectiveShiftClickTestUndo_Recording.xml
  test/core/recorded/SelectiveShiftClickTest_Recording.xml
Labels: LGTM

#9587 DYN-1545: Build performance test suite
  tools/Performance/DynamoPerformanceTests/PerformanceTestFramework.cs
  tools/Performance/DynamoPerformanceTests/README.md
  tools/Performance/DynamoPerformanceTests/graphs/Aniform.dyn
  tools/Performance/DynamoPerformanceTests/graphs/CodeBlocks.dyn
  tools/Performance/DynamoPerformanceTests/graphs/ElementBindingLarge.dyn
  tools/Performance/DynamoPerformanceTests/graphs/HeterogeneousInputsFirst.dyn
  tools/Performance/DynamoPerformanceTests/graphs/HeterogeneousInputsLast.dyn
  tools/Performance/DynamoPerformanceTests/graphs/HomogeneousInputs.dyn
  tools/Performance/DynamoPerformanceTests/graphs/ImportCSV.dyn
  tools/Performance/DynamoPerformanceTests/graphs/Isovist.dyn
  tools/Performance/DynamoPerformanceTests/graphs/JewelCage.dyn
  tools/Performance/DynamoPerformanceTests/graphs/LotsOfColoredStuff.dyn
  tools/Performance/DynamoPerformanceTests/graphs/Math.dyn
  tools/Performance/DynamoPerformanceTests/graphs/Points_40x40x40.dyn
  tools/Performance/DynamoPerformanceTests/graphs/Pottery.dyn
  tools/Performance/DynamoPerformanceTests/graphs/PotteryCustom.dyf
  tools/Performance/DynamoPerformanceTests/graphs/PythonJSONParsing.dyn
  tools/Performance/DynamoPerformanceTests/graphs/TSplinesSrf_to_Mesh.dyn
  tools/Performance/DynamoPerformanceTests/graphs/Vase.dyn
  tools/Performance/DynamoPerformanceTests/graphs/data/helix.csv
  tools/Performance/DynamoPerformanceTests/graphs/data/pokedex.json
  tools/Performance/DynamoPerformanceTests/images/Aniform.PNG
  tools/Performance/DynamoPerformanceTests/images/CSVToStuff.PNG
  tools/Performance/DynamoPerformanceTests/images/CodeBlocks.PNG
  tools/Performance/DynamoPerformanceTests/images/ElementBinding.PNG
  tools/Performance/DynamoPerformanceTests/images/Isovist.PNG
  tools/Performance/DynamoPerformanceTests/images/JewelCage.PNG
  tools/Performance/DynamoPerformanceTests/images/LotsOfColoredStuff.PNG
  tools/Performance/DynamoPerformanceTests/images/Math.PNG
  tools/Performance/DynamoPerformanceTests/images/ParseJSON.PNG
  tools/Performance/DynamoPerformanceTests/images/Points.PNG
  tools/Performance/DynamoPerformanceTests/images/Pottery.PNG
  tools/Performance/DynamoPerformanceTests/images/TSplinesToMesh.PNG
  tools/Performance/DynamoPerformanceTests/images/Vase.PNG
Labels: LGTM

#9586 license cleanup
  LICENSE.txt
  doc/distrib/License.rtf
  extern/Microsoft.Windows.Shell/Microsoft.Windows.Shell.dll
  extern/Microsoft/Release/x64/msvcp110.dll
  extern/Microsoft/Release/x64/msvcr110.dll
  tools/install/InstallSpec.xml
Labels: LGTM

#9589 Update vote button
  src/DynamoCoreWpf/Views/PackageManager/PackageManagerSearchView.xaml
Labels: LGTM

#9594 2.2 license cleanup (#9586)
  LICENSE.txt
  doc/distrib/License.rtf
  extern/Microsoft.Windows.Shell/Microsoft.Windows.Shell.dll
  extern/Microsoft/Release/x64/msvcp110.dll
  extern/Microsoft/Release/x64/msvcr110.dll
  tools/install/InstallSpec.xml
Labels: LGTM

#9578 DYN-1722
  src/Engine/ProtoCore/Lang/CallSite.cs
  src/Engine/ProtoCore/Lang/Replication/ReplicationInstruction.cs
  test/Engine/ProtoTest/Associative/BuiltinMethodsTest.cs
  test/Engine/ProtoTest/Associative/MethodResolution.cs
  test/Engine/ProtoTest/TD/Associative/Replication.cs
Labels: LGTM

#9528 DYN-1541: Issues with code block function default arguments
  src/Engine/ProtoAssociative/CodeGen.cs
  src/Engine/ProtoCore/Parser/AssociativeAST.cs
  test/DynamoCoreTests/CodeBlockNodeTests.cs
  test/DynamoCoreWpfTests/CodeBlockNodeTests.cs
  test/core/recorded/DeleteCrashCommands.xml
Labels: LGTM

#9599 about box updates part 2
  doc/distrib/License.rtf
Labels: PTAL
