Repository DynamoDS/Dynamo, pull requests merged in 2019-11, with the labels that each got.

#10109 Updated transform_all.bat
  src/transform_all.bat
Labels: LGTM

#10096 Convert BigInteger to Int64 when possible from Python
  src/DynamoUtilities/DataMarshaler.cs
  src/DynamoUtilities/DynamoUtilities.csproj
  test/Libraries/DynamoPythonTests/PythonEditTests.cs
  test/Libraries/DynamoPythonTests/PythonEvalTests.cs
  test/core/python/BigIntegerToLong.dyn
Labels: LGTM

#10127 DYN-2273 - Fix crash by compiling null input to null AST node
  src/DynamoCore/Engine/CodeGeneration/AstBuilder.cs
  test/DynamoCoreTests/CustomNodes.cs
  test/DynamoCoreWpfTests/RecordedTests.cs
  test/core/CustomNodes/cbn_customnode_crash.dyf
  test/core/CustomNodes/cbn_customnode_crash.dyn
Labels: LGTM

#10119 Save all workspaces after Dynamo crashes
  src/DynamoCoreWpf/ViewModels/Core/DynamoViewModel.cs
  test/DynamoCoreWpfTests/WorkspaceSaving.cs
Labels: LGTM, error/warning/crash

#10139 bump to 2.6
  src/AssemblySharedInfoGenerator/AssemblySharedInfo.cs
  src/AssemblySharedInfoGenerator/AssemblySharedInfo.tt
Labels: LGTM, priority

#10143 Use Any() with IEnumerable
  src/DynamoCore/Scheduler/UpdateRenderPackageAsyncTask.cs
Labels: LGTM

#9988 Python script editor should provide a workspace ID when updating model
  src/DynamoCore/Models/DynamoModelCommands.cs
  src/Libraries/PythonNodeModelsWpf/PythonNode.cs
  src/Libraries/PythonNodeModelsWpf/ScriptEditorWindow.xaml.cs
  test/Libraries/DynamoPythonTests/PythonEditTests.cs
  test/core/python/PythonCustomNodeHomeWorkspace.dyn
  test/core/python/PythonCustomNodeTest.dyf
Labels: LGTM

#10146 Remove LibG223 dir, add support for LibG for ASM226
  extern/LibG_223_0_1/LibG.AsmPreloader.Managed.dll
  extern/LibG_223_0_1/LibG.AsmPreloader.Unmanaged.dll
  extern/LibG_223_0_1/LibG.Managed.dll
  extern/LibG_223_0_1/LibG.ProtoInterface.dll
  extern/LibG_223_0_1/LibG.dll
  extern/LibG_223_0_1/LibGCore.dll
  extern/LibG_223_0_1/libiconv.dll
  extern/LibG_223_0_1/libintl.dll
  src/DynamoApplications/StartupUtils.cs
  src/DynamoCore/DynamoCore.csproj
  src/Tools/DynamoShapeManager/Preloader.cs
  test/DynamoCoreTests/libGPreloaderTests.cs
  test/Libraries/TestServices/TestSessionConfiguration.cs
Labels: WIP

#10083 DYN-2226: Graphs with large node quantities cause long delays when setting element bound Revit nodes to update
  src/Engine/ProtoCore/Properties/AssemblyInfo.cs
  src/Engine/ProtoCore/RuntimeData.cs
  test/DynamoCoreWpfTests/RecordedTests.cs
Labels: LGTM, performance

#10159 incorrect path in sample hint
  doc/distrib/Samples/en-US/Revit/Revit_Adaptive Component Placement.dyn
  doc/distrib/Samples/en-US/Revit/Revit_Color.dyn
  doc/distrib/Samples/en-US/Revit/Revit_Floors and Framing.dyn
  doc/distrib/Samples/en-US/Revit/Revit_ImportSolid.dyn
  doc/distrib/Samples/en-US/Revit/Revit_PlaceFamiliesByLevel_Set Parameters.dyn
  doc/distrib/Samples/en-US/Revit/Revit_StructuralFraming.dyn
Labels: LGTM

#10169 Update regarding dispose feature in dynamo 2.5 and above
  03-Development-Options/3-4-zerotouch-nodes.html
Labels: LGTM

#10170 Update syswinint to 3.x (align with Revit)
  extern/System.Windows.Interactivity/System.Windows.Interactivity.dll
  src/DynamoCoreWpf/UI/HandlingEventTrigger.cs
Labels: LGTM

#10155 DYN-2240
  src/DynamoCore/Graph/Workspaces/PackageDependencyInfo.cs
  src/DynamoCoreWpf/Views/Core/DynamoView.xaml.cs
  src/WorkspaceDependencyViewExtension/Properties/Resources.Designer.cs
  src/WorkspaceDependencyViewExtension/Properties/Resources.en-US.resx
  src/WorkspaceDependencyViewExtension/Properties/Resources.resx
  src/WorkspaceDependencyViewExtension/WorkspaceDependencyViewExtension.cs
  test/DynamoCoreWpfTests/PackageManagerExtensionLoadingTests.cs
  test/DynamoCoreWpfTests/ViewExtensions/WorkspaceDependencyViewExtensionTests.cs
Labels: LGTM
