Repository DynamoDS/Dynamo, pull requests merged in 2019-07, with the labels that each got.

#9822 DYN-1999 Adding a section for users to provide feedback.
  src/DynamoCoreWpf/Properties/Resources.Designer.cs
  src/DynamoCoreWpf/Properties/Resources.en-US.resx
  src/DynamoCoreWpf/Properties/Resources.resx
  src/DynamoCoreWpf/UI/Themes/Modern/DynamoColorsAndBrushes.xaml
  src/DynamoCoreWpf/Views/Core/DynamoView.xaml
  src/PackageDependencyViewExtension/PackageDependencyView.xaml
  src/PackageDependencyViewExtension/PackageDependencyView.xaml.cs
Labels: LGTM

#9815 Prevent custom node package containing duplicate node definition from loading
  src/DynamoCore/Core/CustomNodeManager.cs
  src/DynamoCore/DynamoCore.csproj
  src/DynamoCore/Exceptions/CustomNodePackageLoadException.cs
  src/DynamoCore/Properties/Resources.Designer.cs
  src/DynamoCore/Properties/Resources.en-US.resx
  src/DynamoCore/Properties/Resources.resx
  src/DynamoCoreWpf/Properties/Resources.Designer.cs
  src/DynamoCoreWpf/Properties/Resources.en-US.resx
  src/DynamoCoreWpf/Properties/Resources.resx
  src/DynamoCoreWpf/ViewModels/PackageManager/PackageManagerClientViewModel.cs
  src/DynamoCoreWpf/ViewModels/PackageManager/PackageManagerSearchViewModel.cs
  src/DynamoCoreWpf/Views/PackageManager/PackageManagerSearchView.xaml.cs
  src/DynamoPackages/PackageLoader.cs
  test/DynamoCoreTests/CustomNodes.cs
  test/DynamoCoreWpfTests/SerializationTests.cs
  test/DynamoCoreWpfTests/WorkspaceSaving.cs
  test/Libraries/PackageManagerTests/PackageLoaderTests.cs
  test/pkgs/EvenOdd/dyf/EvenOdd.dyf
  test/pkgs/EvenOdd/pkg.json
  test/pkgs/EvenOdd2/dyf/EvenOdd.dyf
  test/pkgs/EvenOdd2/pkg.json
Labels: LGTM

#9834 Correct package install error dialog messages
  src/DynamoCore/Properties/Resources.Designer.cs
  src/DynamoCore/Properties/Resources.en-US.resx
  src/DynamoCore/Properties/Resources.resx
  src/DynamoCoreWpf/Properties/Resources.Designer.cs
  src/DynamoCoreWpf/Properties/Resources.en-US.resx
  src/DynamoCoreWpf/Properties/Resources.resx
  src/DynamoCoreWpf/ViewModels/PackageManager/PackageManagerSearchViewModel.cs
Labels: LGTM

#9840 Adding back the width for the splitter between workspace and extensions side bar
  src/DynamoCoreWpf/Views/Core/DynamoView.xaml
Labels: LGTM

#9842 [Cherry-pick #9840] Adding back the width for the splitter between workspace and extensions side bar
  src/DynamoCoreWpf/Views/Core/DynamoView.xaml
Labels: LGTM

#9841 Package B should not overwrite CustomNodes defined in Package A
  src/DynamoCore/Core/CustomNodeDefinition.cs
  src/DynamoCore/Core/CustomNodeManager.cs
  src/DynamoCore/Graph/Workspaces/PackageDependencyInfo.cs
  src/DynamoCore/Properties/Resources.Designer.cs
  src/DynamoCore/Properties/Resources.en-US.resx
  src/DynamoCore/Properties/Resources.resx
  src/DynamoCoreWpf/Properties/Resources.Designer.cs
  src/DynamoCoreWpf/Properties/Resources.en-US.resx
  src/DynamoCoreWpf/Properties/Resources.resx
  src/DynamoCoreWpf/ViewModels/PackageManager/PackageManagerSearchViewModel.cs
  src/DynamoPackages/Package.cs
  src/DynamoPackages/PackageLoader.cs
  src/DynamoPackages/PackageManagerExtension.cs
  test/DynamoCoreTests/CustomNodes.cs
  test/DynamoCoreWpfTests/PublishPackageViewModelTests.cs
  test/DynamoCoreWpfTests/SerializationTests.cs
  test/DynamoCoreWpfTests/WorkspaceSaving.cs
  test/Libraries/PackageManagerTests/PackageLoaderTests.cs
  test/ViewExtensionLibraryTests/LibraryViewControllerTests.cs
  test/pkgs/PackageThatWillBeModified/dyf/ANodeToModify.dyf
  test/pkgs/PackageThatWillBeModified/pkg.json
Labels: PTAL

#9735 Fix comparison operators for double values in DS
  src/Engine/ProtoCore/DSASM/Executive.cs
  src/Engine/ProtoCore/DSASM/Stack.cs
  src/Engine/ProtoCore/Lang/BuiltInFunctionEndPoint.cs
  src/Engine/ProtoCore/Utils/MathUtils.cs
  test/Engine/ProtoTest/Associative/MicroFeatureTests.cs
  test/Engine/ProtoTest/Imperative/MicroFeatureTests.cs
  test/Engine/ProtoTest/TD/DocTests/UserManualTests.cs
Labels: DNM, WIP

#9852 Updating the packages count.
  test/Libraries/PackageManagerTests/PackageLoaderTests.cs
Labels: LGTM

#9855 this test fails when run alone
  test/DynamoCoreWpfTests/NodeViewCustomizationTests.cs
Labels: LGTM

#9859 bump version of master
  src/AssemblySharedInfoGenerator/AssemblySharedInfo.cs
  src/AssemblySharedInfoGenerator/AssemblySharedInfo.tt
Labels: LGTM

#9858 Remove Debug Assertions from CallSite causing VM crash in Debug mode
  src/Engine/ProtoCore/Lang/CallSite.cs
Labels: LGTM

#9860 DYN-2020 - Add test for package dependency state change.
  test/DynamoCoreTests/PackageDependencyTests.cs
  test/Libraries/PackageManagerTests/PackageLoaderTests.cs
  test/core/packageDependencyTests/ClockworkPackage/dyf/Color.Aqua.dyf
  test/core/packageDependencyTests/ClockworkPackage/dyf/Color.Black.dyf
  test/core/packageDependencyTests/ClockworkPackage/extra/LICENSE
  test/core/packageDependencyTests/ClockworkPackage/extra/Readme.txt
  test/core/packageDependencyTests/ClockworkPackage/pkg.json
Labels: LGTM

#9850 Publish Package with Host Multi-Selection
  src/DynamoCoreWpf/Controls/RunSettingsControl.xaml
  src/DynamoCoreWpf/Properties/Resources.Designer.cs
  src/DynamoCoreWpf/Properties/Resources.en-US.resx
  src/DynamoCoreWpf/Properties/Resources.resx
  src/DynamoCoreWpf/UI/Themes/Modern/DynamoColorsAndBrushes.xaml
  src/DynamoCoreWpf/ViewModels/PackageManager/PublishPackageViewModel.cs
  src/DynamoCoreWpf/Views/About/AboutWindow.xaml
  src/DynamoCoreWpf/Views/PackageManager/PublishPackageView.xaml
  src/DynamoCoreWpf/Views/PackageManager/PublishPackageView.xaml.cs
  src/DynamoPackages/Package.cs
  src/DynamoPackages/PackageUploadBuilder.cs
Labels: PTAL

#9781 [Need Feedback] Update Download Status Bar Width
  src/DynamoCoreWpf/Views/PackageManager/PackageManagerSearchView.xaml
Labels: PTAL
