Repository DynamoDS/Dynamo, pull requests merged in 2020-03, with the labels that each got.

#10444 Cover Test for Configuration Folder
  test/DynamoCoreTests/Configuration/ContextTests.cs
  test/DynamoCoreTests/Configuration/ExecutionSessionTests.cs
  test/DynamoCoreTests/Configuration/PreferenceSettingsTests.cs
  test/DynamoCoreTests/DynamoCoreTests.csproj
Labels: LGTM

#10148 Fix for crash while drawing Point manipulator (gizmo) when LibG fails to load
  src/DynamoCoreWpf/Rendering/HelixRenderPackage.cs
  src/DynamoManipulation/NodeManipulator.cs
  src/NodeServices/GraphicsDataInterfaces.cs
Labels: LGTM

#10462 Mesh display using shaders
  src/DynamoCoreWpf/DynamoCoreWpf.csproj
  src/DynamoCoreWpf/Properties/Resources.Designer.cs
  src/DynamoCoreWpf/Properties/Resources.en-US.resx
  src/DynamoCoreWpf/Properties/Resources.resx
  src/DynamoCoreWpf/ViewModels/Watch3D/AttachedProperties.cs
  src/DynamoCoreWpf/ViewModels/Watch3D/DynamoEffectsManager.cs
  src/DynamoCoreWpf/ViewModels/Watch3D/DynamoGeometryModel3D.cs
  src/DynamoCoreWpf/ViewModels/Watch3D/HelixWatch3DViewModel.cs
  src/DynamoCoreWpf/ViewModels/Watch3D/compiledShaders/psDynamoMesh
  src/DynamoCoreWpf/ViewModels/Watch3D/compiledShaders/vsDynamoMesh
  src/DynamoCoreWpf/ViewModels/Watch3D/shaderSource/CompileShaders.bat
  src/DynamoCoreWpf/ViewModels/Watch3D/shaderSource/DynamoCommonStructures.hlsl
  src/DynamoCoreWpf/ViewModels/Watch3D/shaderSource/helix_shader_defs/COMMON/Common.hlsl
  src/DynamoCoreWpf/ViewModels/Watch3D/shaderSource/helix_shader_defs/COMMON/CommonBuffers.hlsl
  src/DynamoCoreWpf/ViewModels/Watch3D/shaderSource/helix_shader_defs/COMMON/DataStructs.hlsl
  src/DynamoCoreWpf/ViewModels/Watch3D/shaderSource/psDynamoMesh.hlsl
  src/DynamoCoreWpf/ViewModels/Watch3D/shaderSource/readme.md
  src/DynamoCoreWpf/ViewModels/Watch3D/shaderSource/vsDynamoMesh.hlsl
  src/NodeServices/GraphicsDataInterfaces.cs
  src/VisualizationTests/HelixWatch3DViewModelTests.cs
Labels: Graphics, LGTM, PTAL

#10466 Headlight bound to Camera LookDirection
  src/DynamoCoreWpf/ViewModels/Watch3D/HelixWatch3DViewModel.cs
  src/DynamoCoreWpf/ViewModels/Watch3D/compiledShaders/psDynamoMesh
  src/DynamoCoreWpf/ViewModels/Watch3D/compiledShaders/vsDynamoMesh
  src/DynamoCoreWpf/ViewModels/Watch3D/shaderSource/psDynamoMesh.hlsl
  src/VisualizationTests/HelixWatch3DViewModelTests.cs
Labels: Graphics, LGTM, PTAL

#10498 DYN-2501 - Increase Code Coverage - Migration
  test/DynamoCoreTests/DynamoCoreTests.csproj
  test/DynamoCoreTests/Migration/MigrationReportTests.cs
  test/DynamoCoreTests/Migration/MigrationTests.cs
  test/DynamoCoreTests/Migration/WorkspaceMigrationsTests.cs
Labels: LGTM

#10487 add 3d graphics image comparison tests
  src/DynamoCoreWpf/ViewModels/Watch3D/HelixWatch3DViewModel.cs
  src/VisualizationTests/HelixImageComparisonTests.cs
  src/VisualizationTests/WpfVisualizationTests.csproj
  test/core/visualization/imageComparison/linecolors.dyn
  test/core/visualization/imageComparison/pointcolors.dyn
  test/core/visualization/imageComparison/referenceImages/IsolateAllMeshGeometryRender.png
  test/core/visualization/imageComparison/referenceImages/StandardFrozenMeshGeometryRender.png
  test/core/visualization/imageComparison/referenceImages/StandardMeshGeometryRender.png
  test/core/visualization/imageComparison/referenceImages/StandardSelectedMeshGeometryRender.png
  test/core/visualization/imageComparison/referenceImages/VertColorFrozenMeshGeometryRender.png
  test/core/visualization/imageComparison/referenceImages/VertColorSelectedMeshGeometryRender.png
  test/core/visualization/imageComparison/referenceImages/directManipulator.png
  test/core/visualization/imageComparison/referenceImages/lines.png
  test/core/visualization/imageComparison/referenceImages/linesFrozen.png
  test/core/visualization/imageComparison/referenceImages/linesIsolated.png
  test/core/visualization/imageComparison/referenceImages/linesSelected.png
  test/core/visualization/imageComparison/referenceImages/points.png
  test/core/visualization/imageComparison/referenceImages/pointsFrozen.png
  test/core/visualization/imageComparison/referenceImages/pointsIsolated.png
  test/core/visualization/imageComparison/referenceImages/pointsSelected.png
  test/core/visualization/imageComparison/spherecolors.dyn
Labels: Graphics, LGTM, PTAL

#10497 target shader model 4 to avoid crash when user does not have GPU.
  src/DynamoCoreWpf/ViewModels/Watch3D/compiledShaders/psDynamoMesh
  src/DynamoCoreWpf/ViewModels/Watch3D/compiledShaders/vsDynamoMesh
  src/DynamoCoreWpf/ViewModels/Watch3D/shaderSource/CompileShaders.bat
Labels: Graphics, PTAL

#10433 Use libg_225_0_0 in the config
  extern/ProtoGeometry/ProtoGeometry.config
Labels: LGTM

#10499 Increase Core folder test coverage
  test/DynamoCoreTests/AuthenticationManagerTests.cs
Labels: LGTM

#10493 [DYN-1815] Dynamo package install invalid package (sad path) error and crash
  src/DynamoCoreWpf/Properties/Resources.Designer.cs
  src/DynamoCoreWpf/Properties/Resources.en-US.resx
  src/DynamoCoreWpf/Properties/Resources.resx
  src/DynamoCoreWpf/ViewModels/PackageManager/PackageManagerClientViewModel.cs
  src/DynamoPackages/PackageLoader.cs
  test/DynamoCoreWpfTests/PackageManagerUITests.cs
  test/pkgs/Autodesk Steel Package/steel-pkg/dyf/Filter by I and C section shapes.dyf
  test/pkgs/Autodesk Steel Package/steel-pkg/pkg.json
Labels: PTAL

#10511 Update PackageManagerExtensionLoadingTests.cs
  test/DynamoCoreWpfTests/PackageManagerExtensionLoadingTests.cs
Labels: LGTM

#10506 fix shader interpolation and make image comparison tests more tolerant.
  src/DynamoCoreWpf/ViewModels/Watch3D/compiledShaders/psDynamoMesh
  src/DynamoCoreWpf/ViewModels/Watch3D/compiledShaders/vsDynamoMesh
  src/DynamoCoreWpf/ViewModels/Watch3D/shaderSource/DynamoCommonStructures.hlsl
  src/DynamoCoreWpf/ViewModels/Watch3D/shaderSource/psDynamoMesh.hlsl
  src/DynamoCoreWpf/ViewModels/Watch3D/shaderSource/vsDynamoMesh.hlsl
  src/VisualizationTests/HelixImageComparisonTests.cs
Labels: Graphics, PTAL
