Repository DynamoDS/Dynamo, pull requests merged in 2020-08, with the labels that each got.

#10928 T1.3 save python2 backup file
  src/Libraries/PythonNodeModels/PythonNode.cs
  src/Libraries/PythonNodeModelsWpf/Properties/AssemblyInfo.cs
  src/Libraries/PythonNodeModelsWpf/ScriptEditorWindow.xaml
  src/PythonMigrationViewExtension/Controls/VisualDifferenceViewer.xaml.cs
  src/PythonMigrationViewExtension/GraphPythonDependencies.cs
  src/PythonMigrationViewExtension/IronPythonInfoDialog.xaml.cs
  src/PythonMigrationViewExtension/MigrationAssistant/PythonMigrationAssistantViewModel.cs
  src/PythonMigrationViewExtension/MigrationAssistant/ScriptMigrator.cs
  src/PythonMigrationViewExtension/MigrationAssistant/migrate_2to3.py
  src/PythonMigrationViewExtension/Properties/Resources.Designer.cs
  src/PythonMigrationViewExtension/Properties/Resources.en-US.resx
  src/PythonMigrationViewExtension/Properties/Resources.resx
  src/PythonMigrationViewExtension/PythonMigrationAssistantViewModel.cs
  src/PythonMigrationViewExtension/PythonMigrationViewExtension.cs
  src/PythonMigrationViewExtension/PythonMigrationViewExtension.csproj
  test/DynamoCoreWpfTests/ViewExtensions/PythonMigrationViewExtensionTests.cs
  test/core/python/2to3Test.dyn
Labels: Python

#10932 T1.5-Modify the VisualDifferenceViewer so text wraps instead of using scrollviewers
  src/PythonMigrationViewExtension/Controls/BaseDiffViewer.xaml
  src/PythonMigrationViewExtension/Controls/BaseDiffViewer.xaml.cs
  src/PythonMigrationViewExtension/Controls/InLineControl.xaml
  src/PythonMigrationViewExtension/Controls/InLineControl.xaml.cs
  src/PythonMigrationViewExtension/Controls/SideBySideControl.xaml
  src/PythonMigrationViewExtension/Controls/SideBySideControl.xaml.cs
  src/PythonMigrationViewExtension/Controls/VisualDifferenceViewer.xaml.cs
  src/PythonMigrationViewExtension/Differ/IDiffViewViewModel.cs
  src/PythonMigrationViewExtension/Differ/InLineViewModel.cs
  src/PythonMigrationViewExtension/Differ/RichTextBoxHandler.cs
  src/PythonMigrationViewExtension/Differ/SideBySideViewModel.cs
  src/PythonMigrationViewExtension/GraphPythonDependencies.cs
  src/PythonMigrationViewExtension/MigrationAssistant/PythonMigrationAssistantViewModel.cs
  src/PythonMigrationViewExtension/PythonMigrationViewExtension.cs
  src/PythonMigrationViewExtension/PythonMigrationViewExtension.csproj
  test/DynamoCoreWpfTests/ViewExtensions/PythonMigrationViewExtensionTests.cs
Labels: Python, UI

#10986 Update ScriptEditorWindow.xaml
  src/Libraries/PythonNodeModelsWpf/ScriptEditorWindow.xaml
Labels: PTAL

#10977 Sys.path value should be limited to the scope of the python node(CPython3 Engine)
  src/Libraries/DSCPython/CPythonEvaluator.cs
  test/Libraries/DynamoPythonTests/PythonEditTests.cs
  test/core/python/CPythonSysPath.dyn
Labels: PTAL

#10983 CPython eval always fails
  src/Libraries/DSCPython/CPythonEvaluator.cs
  test/Libraries/DynamoPythonTests/DynamoPythonTests.csproj
  test/Libraries/DynamoPythonTests/PythonEvalTests.cs
Labels: PTAL

#11022 [DYN-2988] Add custom fixer for instance.None
  src/PythonMigrationViewExtension/MigrationAssistant/migrate_2to3.py
  src/PythonMigrationViewExtension/MigrationAssistant/python_migration_fixers/fix_none.py
  src/PythonMigrationViewExtension/PythonMigrationViewExtension.csproj
  test/DynamoCoreTests/PythonMigrationAssistantTests.cs
Labels: PTAL

#10972 Allow integer slider to support 64 bit ints
  src/DynamoCore/Graph/Workspaces/SerializationExtensions.cs
  src/DynamoCore/Graph/Workspaces/WorkspaceModel.cs
  src/Engine/ProtoCore/Parser/AssociativeAST.cs
  src/Libraries/CoreNodeModels/CoreNodeModelsImages.resx
  src/Libraries/CoreNodeModels/Input/BaseTypes.cs
  src/Libraries/CoreNodeModels/Input/BasicInteractive.cs
  src/Libraries/CoreNodeModels/Input/IntegerSlider.cs
  src/Libraries/CoreNodeModels/Input/SliderBase.cs
  src/Libraries/CoreNodeModelsWpf/NodeViewCustomizations/IntegerSlider.cs
  src/Resources/CoreNodeModels/LargeIcons/CoreNodeModels.Input.IntegerSlider64Bit.Large.png
  src/Resources/CoreNodeModels/SmallIcons/CoreNodeModels.Input.IntegerSlider64Bit.Small.png
  test/DynamoCoreTests/DynamoDefects.cs
  test/DynamoCoreTests/SerializationTests.cs
  test/DynamoCoreWpfTests/RecordedTests.cs
  test/DynamoCoreWpfTests/SliderTests.cs
  test/Libraries/CoreNodesTests/NodeWithUITests.cs
  test/ViewExtensionLibraryTests/resources/libraryItems.json
  test/core/recorded/UpdateNodeContents.xml
Labels: PTAL
