Repository DynamoDS/Dynamo, pull requests merged in 2021-12, with the labels that each got.

#12396 use aggregated exception type to log aggregated xaml parse exceptions
  extern/Analytics.NET/Analytics.NET.Core.dll
  extern/Analytics.NET/Analytics.NET.Google.dll
  extern/Analytics.NET/Analytics.Net.ADP.dll
  src/DynamoCoreWpf/UI/InOutPortPanel.cs
Labels: WIP

#12380 Turn Microsoft.Xaml.Behaviors into Dynamo.Xaml.Behaviors!
  extern/Microsoft.Xaml.Behaviors/Dynamo.Microsoft.Xaml.Behaviors.dll
  extern/System.Windows.Interactivity/System.Windows.Interactivity.dll
  extern/legacy_remove_me/bin/System.Windows.Interactivity.dll
  src/Dynamo.All.sln
  src/DynamoCoreWpf/DynamoCoreWpf.csproj
  src/DynamoCoreWpf/UI/HandlingEventTrigger.cs
  src/DynamoCoreWpf/UI/MouseBehaviour.cs
  src/DynamoCoreWpf/UI/Themes/Modern/Connectors.xaml
  src/DynamoCoreWpf/UI/Themes/Modern/InPorts.xaml
  src/DynamoCoreWpf/UI/Themes/Modern/OutPorts.xaml
  src/DynamoCoreWpf/UI/Themes/Modern/Ports.xaml
  src/LibraryViewExtension/LibraryViewExtension.csproj
  src/Tools/AssemblyRenamerCLI/App.config
  src/Tools/AssemblyRenamerCLI/AssemblyRenamerCLI.csproj
  src/Tools/AssemblyRenamerCLI/Program.cs
  src/Tools/AssemblyRenamerCLI/Properties/AssemblyInfo.cs
  src/Tools/AssemblyRenamerCLI/originalBinaries/Microsoft.Xaml.Behaviors.dll
  src/Tools/AssemblyRenamerCLI/packages.config
  src/Tools/AssemblyRenamerCLI/readme.md
Labels: PTAL

#12484 RC2.13 make nugets stable
  tools/NuGet/BuildPackages.bat
Labels: DNM

#12306 convert to sdk style
  src/Config/CS.props
  src/Config/CS_SDK.props
  src/Dynamo.All.sln
  src/Engine/GraphLayout/GraphLayout.csproj
  src/Engine/ProtoCore/DSASM/Mirror/ExecutionMirror.cs
  src/Engine/ProtoCore/ProtoCore.csproj
Labels: PTAL
