Repository DynamoDS/Dynamo, pull requests merged in 2022-04, with the labels that each got.

#11921 DYN-4230 Callsite ExecWithRISlowPath optimizations to improve Cross Product replication performance
  src/Engine/ProtoCore/Lang/CallSite.cs
Labels: performance

#12801 wrap launch darkly in CLI to avoid bringing in new deps
  src/Dynamo.All.sln
  src/DynamoCore/Logging/AnalyticsService.cs
  src/DynamoCore/Models/DynamoModel.cs
  src/DynamoCoreWpf/Views/Core/DynamoView.xaml.cs
  src/DynamoUtilities/DynamoFeatureFlagsManager.cs
  src/DynamoUtilities/Md2Html.cs
  src/NodeServices/Analytics.cs
  src/Tools/DynamoFeatureFlags/App.config
  src/Tools/DynamoFeatureFlags/DynamoFeatureFlags.csproj
  src/Tools/DynamoFeatureFlags/FeatureFlagsClient.cs
  src/Tools/DynamoFeatureFlags/Program.cs
  src/Tools/DynamoFeatureFlags/Properties/AssemblyInfo.cs
  src/Tools/Md2Html/Program.cs
  test/DynamoCoreTests/DynamoCoreTests.csproj
  test/DynamoCoreTests/ExtensionTests.cs
  test/DynamoCoreTests/Logging/FeatureFlagTests.cs
Labels: PTAL

#9485 [DNM] Optimize live execution of modified graphs
  src/DynamoCore/Engine/EngineController.cs
  src/Engine/ProtoAssociative/CodeGen.cs
  src/Engine/ProtoAssociative/CodeGen_SSA.cs
  src/Engine/ProtoCore/AssociativeGraph.cs
  src/Engine/ProtoCore/DSASM/Executive.cs
  src/Engine/ProtoCore/DSASM/InstructionSet.cs
  src/Engine/ProtoCore/DSASM/Stack.cs
  src/Engine/ProtoCore/Lang/FunctionPointerEvaluator.cs
  src/Engine/ProtoCore/Parser/AssociativeAST.cs
  src/Engine/ProtoCore/RuntimeCore.cs
  src/Engine/ProtoCore/Utils/CoreUtils.cs
  src/Engine/ProtoScript/Runners/LiveRunner.cs
  test/Engine/ProtoTest/LiveRunnerTests/MemoryConsumptionTests.cs
Labels: DNM

#10355 DYN-4228 Convert StrongConnectComponent to use List vs Dictionary input type
  src/Engine/ProtoAssociative/CodeGen.cs
Labels: performance
