Repository DynamoDS/Dynamo, pull requests merged in 2025-06, with the labels that each got.

#16256 DYN-8906 : introduce autocomplete search combo
  src/DynamoCoreWpf/UI/Themes/Modern/DynamoConverters.xaml
  src/DynamoCoreWpf/UI/Themes/Modern/DynamoModern.xaml
  src/NodeAutoCompleteViewExtension/ViewModels/NodeAutoCompleteBarViewModel.cs
  src/NodeAutoCompleteViewExtension/Views/NodeAutoCompleteBarView.xaml
Labels: ai/ml

#16265 DYN-8564: run autocomplete search in background thread
  src/DynamoCoreWpf/Controls/NodeAutoCompleteSearchControl.xaml
  src/DynamoCoreWpf/PublicAPI.Unshipped.txt
  src/DynamoCoreWpf/ViewModels/Search/NodeAutoCompleteSearchViewModel.cs
  src/NodeAutoCompleteViewExtension/ViewModels/NodeAutoCompleteBarViewModel.cs
Labels: ai/ml

#16188 DYN-8896 Code Only Node View
  src/DynamoCoreWpf/Controls/InPorts.xaml
  src/DynamoCoreWpf/Controls/InPorts.xaml.cs
  src/DynamoCoreWpf/Controls/OutPorts.xaml
  src/DynamoCoreWpf/Controls/OutPorts.xaml.cs
  src/DynamoCoreWpf/DynamoCoreWpf.csproj
  src/DynamoCoreWpf/PublicAPI.Unshipped.txt
  src/DynamoCoreWpf/UI/Themes/Modern/DataTemplates.xaml
  src/DynamoCoreWpf/UI/Themes/Modern/DynamoColorsAndBrushes.xaml
  src/DynamoCoreWpf/UI/Themes/Modern/InPortsOld.xaml
  src/DynamoCoreWpf/UI/Themes/Modern/OutPortsOld.xaml
  src/DynamoCoreWpf/ViewModels/Core/PortViewModel.cs
  src/DynamoCoreWpf/Views/Core/AnnotationView.xaml.cs
  src/DynamoCoreWpf/Views/Core/NodeView.xaml
  src/DynamoCoreWpf/Views/Core/NodeView.xaml.cs
  test/DynamoCoreWpf3Tests/NodeViewCustomizationTests.cs
  test/DynamoCoreWpf3Tests/NodeViewTests.cs
Labels: performance

#16261 Merge master-localization into master
  src/NodeServices/Properties/Resources.cs-CZ.resx
  src/NodeServices/Properties/Resources.de-DE.resx
  src/NodeServices/Properties/Resources.es-ES.resx
  src/NodeServices/Properties/Resources.fr-FR.resx
  src/NodeServices/Properties/Resources.it-IT.resx
  src/NodeServices/Properties/Resources.ja-JP.resx
  src/NodeServices/Properties/Resources.ko-KR.resx
  src/NodeServices/Properties/Resources.pl-PL.resx
  src/NodeServices/Properties/Resources.pt-BR.resx
  src/NodeServices/Properties/Resources.ru-RU.resx
  src/NodeServices/Properties/Resources.zh-CN.resx
  src/NodeServices/Properties/Resources.zh-TW.resx
Labels: ContinuousLocalization

#16286 DYN-8905: Adapt layout algorithm for both input and output
  src/DynamoCore/Graph/Workspaces/LayoutExtensions.cs
  src/DynamoCoreWpf/Utilities/NodeAutoCompleteUtilities.cs
  src/DynamoCoreWpf/ViewModels/Search/NodeSearchElementViewModel.cs
  src/Engine/GraphLayout/GraphLayout.cs
  src/NodeAutoCompleteViewExtension/ViewModels/NodeAutoCompleteBarViewModel.cs
Labels: ai/ml
